// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Open.Social.Core.EF.SessionManager;
using System;

namespace Open.Social.Core.EF.Migrations
{
    [DbContext(typeof(DBOpen))]
    [Migration("20171211212358_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Open.Social.Core.Model.User.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("UserID");

                    b.Property<DateTime>("birth");

                    b.Property<DateTime>("created");

                    b.Property<string>("email");

                    b.Property<DateTime>("expire");

                    b.Property<string>("name")
                        .HasColumnName("name")
                        .HasMaxLength(150);

                    b.Property<string>("password");

                    b.Property<byte[]>("photo");

                    b.Property<Guid>("salt");

                    b.Property<DateTime>("update");

                    b.HasKey("id");

                    b.ToTable("Tbo_User");
                });
#pragma warning restore 612, 618
        }
    }
}
